import { getPostBySlug, getPosts } from "@/lib/posts";
import { notFound } from "next/navigation";

export function generateStaticParams() {

  return getPosts().map((post) => {
    slug: post.slug;
  });
}

type BlogPostParams = { params: { slug: string } };

export default async function BlogPostPage({ params }: BlogPostParams) {

  const post = getPostBySlug(params.slug);

  // Handle 404 errors from undefined url slugs 
  if (!post) {
    notFound();
  }

  return (

    <>
      <h1 className="text-2xl font-bold mt-8 mb-6">{post.title}</h1>
      {/* Insert the markdown blog post as HTML (generated by Contentlayer)  */}
      <div dangerouslySetInnerHTML={{ __html: post.body.html }} className="prose dark:prose-invert"></div>
    </>

  );
}